#!/usr/bin/env bash
#
# manpages-environ-linux v1.2
#
# Extract environment variable names from Linux manual pages
# (ensure that /usr/libexec/makewhatis has been executed)
#
# Written By:   Derek Callaway [decal (AT) sdf {D0T} org]
# Last Updated: Sat Apr 21 10:08:23 PDT 2018
# Tested On:    Ubuntu 16.04.3 LTS
#

PAGER=cat

for m in $(man -k ' ' | awk -F\( '{print$1}')
  do declare -i aline=$(man -- "$m" | grep -n 'ENVIRONMENT' | tail -n 1 | awk -F: '{print$2}')
  declare -a names=( )

  names+=$(PAGER=cat man most | tail -n +${aline} | egrep '^[ ]+[A-Z_, ]+$' | awk -F, '{print$1}')
  names+=$(PAGER=cat man most | tail -n +${aline} | egrep '^[ ]+[A-Z_, ]+$' | awk -F, '{print$2}')
  names+=$(PAGER=cat man most | tail -n +${aline} | egrep '^[ ]+[A-Z_, ]+$' | awk -F, '{print$3}')
  names+=$(PAGER=cat man most | tail -n +${aline} | egrep '^[ ]+[A-Z_, ]+$' | awk -F, '{print$4}')

  echo "$names"
done

exit 0
