#!/usr/bin/env bash
#
# Parse peering codes from SIPBroker's web site
#


lynx -dump http://www.sipbroker.com/sipbroker/action/providerWhitePages\?pageNumber={1,2,3,4,5,6,7,8,9,10,11} >> peering-codes.html

perl -pe 's/[^[:ascii:]]//g' peering-codes.html > peering-codes.txt

egrep 'gif\]  [*]' peering-codes.txt | cut -d ']' -f2- | cut -d '[' -f1 | sed 's!^[ ]*!!' > sipbroker-peering-codes.txt

rm -f peering-codes.txt peering-codes.html

exit 0
