#!/usr/bin/env bash
#
# Create `inet-services/inet-services-all.txt`
#
# Note: needs to run on macOS because of `sed -E`
#

sort -u inet-services/*services-*.txt | sed 's!#.*$!!' | sed -E 's!0[.][0-9]+!!' | grep / | awk '{print$1 " " $2}' | sort -u

exit 0
