#!/usr/bin/env bash
#
# Check each folder's index.md file out of the code repository
# in case they were mistakenly removed.. 
#

read -t 2 -p "Are you sure you want to checkout each directory's index.md file from the repository (this should only be done if they were removed by mistake)? [y/N]: " ANSWER

[ "$ANSWER" -a "${ANSWER[0]}" != "y" -a "${ANSWER[0]}" != "Y" ] && exit 1

while [ ! -d .git ] 
  do cd ..

  declare cdirname=$( basename `pwd` )
  [[ $cdirname == 'GIT' ]] && exit 1
done

declare -a xdirnames=$( find . -maxdepth 1 -type d -not -name '.*' -print )

for d in ${xdirnames[*]}
  do cd -- "`basename $d`"

  [ $? -ne 0 ] && continue

  mv index.md index.md.bak 

  git checkout index.md

  [ -f index.md ] && rm -f index.md.bak 

  cd ..
done

exit 0
