#!/usr/bin/env bash
#
# Check each folder's index.lst file out of the code repository
# in case they were mistakenly removed.. 
#

declare -a xdirnames=$( find . -maxdepth 1 -type d -print )

while [ ! -d .git ] 
  do cd ..

  declare cdirname=$( basename `pwd` )
  [[ $cdirname == 'GIT' ]] && exit 1
done

for d in ${xdirnames[*]}
  do cd -- /home/super/GIT/decal/werdlists/"`basename $d`"
  mv index.lst index.lst.bak 2>/dev/null
  git checkout index.lst
done

exit 0
