#!/usr/bin/env bash
#
# Extract environment variable names from Linux manual pages
#

PAGER=cat

for m in $(man -k '' | awk -F\( '{print$1}')
  do declare -i aline="$(man -- $m | grep -n 'ENVIRONMENT' | tail -n 1 | awk -F: '{print$2}')"
  declare -a names=( )

  names+=$(PAGER=cat man most | tail -n +${aline} | egrep '^[ ]+[A-Z_, ]+$' | awk -F, '{print$1}')
  names+=$(PAGER=cat man most | tail -n +${aline} | egrep '^[ ]+[A-Z_, ]+$' | awk -F, '{print$2}')
  names+=$(PAGER=cat man most | tail -n +${aline} | egrep '^[ ]+[A-Z_, ]+$' | awk -F, '{print$3}')
  names+=$(PAGER=cat man most | tail -n +${aline} | egrep '^[ ]+[A-Z_, ]+$' | awk -F, '{print$4}')
done

exit 0
