#!/usr/bin/env bash
#
# Make a pathname list from `.gitignore` files found in GitHub repositories that
# have been mirrored with `githose` (see <https://github.com/decal/githose>.)
#
# sort -u ~/github/*/*/.gitignore > /tmp/gitignore.out

tr -d '*' < /tmp/gitignore.out | egrep -v '#' | egrep -v '^[[:space:]]*$' | sed -r 's!^[.]?[/]+!!g' | sort -u > /tmp/g.out

for p in $(egrep '/$' /tmp/g.out)
  do declare apath=$(echo $p | sed 's!/$!!')
  egrep -v "^{$apath}$" /tmp/g.out > /tmp/g2.out 2>/dev/null
  [ $? -ne 0 ] && rm /tmp/g2.out && continue
  mv /tmp/g2.out /tmp/g.out
done

tr -d '\015' < /tmp/g.out | sed -r 's![[:space:]]+$!!g' | sed -r 's!^[[:space:]]+!!g' |  egrep -v '(\[|\])' | sed -r 's/^[!]//g' | egrep -i '^[0-9a-z._]' | sort -u  > /tmp/g3.out

exit 0
