#!/usr/bin/env bash
#

[ -f colors ] && source -- colors

if [ ! -d webapp-files ]
  then cd ..

  if [ ! -d webapp-files ]
    then echo -e "${blackfg}${yellowbg}***${reset} ${yellow}Try running this script from the git repository root or bin directory!${reset}"

    exit 1
  else
    cd webapp-files
  fi
else
  cd webapp-files
fi

declare -a file_exts=$( ls -1 *.txt | awk -F- '{print$1}' )

for w in ${file_exts[*]}
  do declare -i acnt=`echo ${file_exts[*]} | tr ' ' '\n' | grep "${w}" | wc -l`

  if [ $acnt -gt 1 ] 
    then if [ ! -d ${w}-all.txt ] 
      then echo -e "${blackf}${greenb}***${reset} ${greenf}Creating all file${bold}:${bold} ${w}-all.txt"
      sort -u ${w}-*.txt > ${w}-all.txt
    fi
  fi
done

echo -e "${blackf}${greenb}***${reset} ${greenf}Creating all file ${bold}:${bold} ${w}-all.txt"
sort -u *.txt > all.txt

exit 0
