#!/usr/bin/env bash
#
# parse-header-constants v1.1
#
# Written By:   Derek Callaway [decal (AT) sdf {D0T} org]
# Last Updated: Sat Apr 21 10:03:33 PDT 2018
# Tested On:    Ubuntu 16.04.3 LTS
#               Darwin 17.5.0 Darwin Kernel Version 17.5.0: Mon Mar  5 22:24:32 PST 2018; root:xnu-4570.51.1~1/RELEASE_X86_64 x86_64 i386
# Use Case:     parse-header-constants /usr/include
#

if [ ! "$1" ]
  then echo 
  echo "usage: $0 INCDIR"
  echo
  echo '  INCDIR  include directory where header files are to be found'
  echo
  echo ex. $0 /usr/include
  echo

  exit 1
fi

find $1 -type f -iname '*.h' -exec egrep '^[#]define ' {} \; | \
  awk '{print$2}' | egrep '^[A-Z]+' | grep -v '(' | sort -u 

exit 0
