#!/usr/bin/env bash
#
# Shorten hyperlinks within the markdown syntax of the given file
#

[ ! -d scripts ] && echo

[ -f scripts/shared/colors ] && source scripts/shared/colors
[ -f scripts/shared/env ] && source scripts/shared/env 

if [ ! "$1" ]
  then echo -e "${reset}"
  echo -ne "${purplef}"
  dos2unix --version 2>&1
  echo -e "${reset}"
  echo -ne "${whitef}"
  mv --version 2>&1 
  echo -e "${reset}"
  echo -ne "${redf}"
  cp --version 2>&1
  echo -e "${reset}"
  echo -e "${yellowf}usage${boldon}:${reset} ${bluef}${ulon}$0${reset} ${greenb}MDFILE${reset}"
  echo -e "  ${greenb}MDFILE${reset}  ${italicson}markdown file containing links to rewrite${reset}"
  echo 

  exit 1
fi

echo -ne "${redf}"

cp -v -- "$1" "/tmp/${1}.${RANDOM}" 2>&1

echo -e "${reset}"

declare achar="$(echo '$1' | sed -r 's!([A-Z]{1}).*$!\1!g')"
declare afile="${achar}.md"

sed 's!http://en.wikipedia.org!https://en.wikipedia.org!g' "$1" | \
  sed 's!https://en.wikipedia.org!https://wikipedia.org!g' | \
  sed 's!http://wikipedia.org!https://wikipedia.org!g' > "$afile"

## TODO: 's!http://host.dom:80!http://host.dom!g' 's!https://host.dom:443!https://host.dom!g'

echo -ne "${whitef}"

mv -v -- "$afile" "$1" 2>&1

echo -e "${reset}"

echo -ne "${purplef}"

dos2unix -- "$1" 2>&1

echo -e "${reset}"

exit 0
